import type {
  Attribute,
  Skill,
  Quest,
  Milestone,
  Journey,
  StoreItem,
  FocusSession,
  UserStats,
} from './types'

export const userStats: UserStats = {
  gems: 600,
  tokens: 90,
  level: 12,
  attributes: [
    { name: 'Charisma', value: 13 },
    { name: 'Vitality', value: 18 },
    { name: 'Intelligence', value: 20 },
    { name: 'Persistence', value: 16 },
    { name: 'Resilience', value: 20 },
    { name: 'Leadership', value: 10 },
  ],
}

export const skills: Skill[] = [
  {
    id: '1',
    name: 'iOS Development',
    category: 'Software Engineering',
    categoryIcon: '👷',
    level: 2,
    currentXP: 9,
    maxXP: 45,
    totalTime: '54m',
    color: '#ff6b9d',
  },
  {
    id: '2',
    name: 'JavaScript',
    category: 'Software Engineering',
    categoryIcon: '👷',
    level: 3,
    currentXP: 14,
    maxXP: 60,
    totalTime: '1h 44m',
    color: '#6b8cff',
  },
  {
    id: '3',
    name: 'Calculus',
    category: 'College',
    categoryIcon: '🎓',
    level: 0,
    currentXP: 11,
    maxXP: 15,
    totalTime: '11m',
    color: '#00d4ff',
  },
  {
    id: '4',
    name: 'Electric Guitar',
    category: 'Music Production',
    categoryIcon: '🎵',
    level: 1,
    currentXP: 5,
    maxXP: 30,
    totalTime: '23m',
    color: '#c44dff',
  },
  {
    id: '5',
    name: 'Figma',
    category: 'Design',
    categoryIcon: '🎨',
    level: 2,
    currentXP: 28,
    maxXP: 50,
    totalTime: '45m',
    color: '#ff8fab',
  },
  {
    id: '6',
    name: 'Calligraphy',
    category: 'Art',
    categoryIcon: '✒️',
    level: 1,
    currentXP: 12,
    maxXP: 25,
    totalTime: '32m',
    color: '#ffa500',
  },
]

export const journeys: Journey[] = [
  {
    id: '1',
    title: 'Become an Indie Developer',
    icon: '💻',
    description:
      'Becoming an indie developer gives me the freedom to create what I am passionate about, work on my own terms, and shape my own path.',
    category: 'Work',
    categoryColor: '#ffa500',
    startDate: '2024-12-19',
    milestonesCount: 2,
    questsCount: 4,
  },
  {
    id: '2',
    title: 'Stay Healthy and Energetic',
    icon: '🌱',
    description:
      'Staying healthy allows me to fully enjoy life and pursue my goals with energy and focus. It helps me feel good physically and mentally, making it easier to connect with others and handle challenges with resilience.',
    category: 'Health',
    categoryColor: '#22c55e',
    startDate: '2024-12-22',
    milestonesCount: 1,
    questsCount: 2,
  },
  {
    id: '3',
    title: 'Stay Connected with Love Ones',
    icon: '💕',
    description:
      'Maintaining strong relationships with family and friends brings joy and support to my life.',
    category: 'Relationships',
    categoryColor: '#ec4899',
    startDate: '2024-12-20',
    milestonesCount: 1,
    questsCount: 2,
  },
]

export const milestones: Milestone[] = [
  {
    id: '1',
    title: 'Launch an app',
    icon: '🚀',
    daysLeft: 9,
    type: 'Major',
    gemReward: 500,
    status: 'In Progress',
    journeyId: '1',
  },
  {
    id: '2',
    title: 'Reach 1000 users',
    icon: '👥',
    daysLeft: 30,
    type: 'Major',
    gemReward: 1000,
    status: 'Not Started',
    journeyId: '1',
  },
  {
    id: '3',
    title: 'Lose weight to 120lbs',
    icon: '⚖️',
    daysLeft: 40,
    type: 'Major',
    gemReward: 500,
    status: 'In Progress',
    journeyId: '2',
  },
]

export const quests: Quest[] = [
  {
    id: '1',
    title: 'Code for 4 hrs',
    icon: '💻',
    difficulty: 'Hard',
    frequency: 'Daily',
    tokenReward: 50,
    statBonuses: [
      { stat: 'Logic', value: 5 },
      { stat: 'Intelligence', value: 5 },
    ],
    journeyId: '1',
    completed: false,
  },
  {
    id: '2',
    title: 'Build the app for 4hrs',
    icon: '🔧',
    difficulty: 'Medium',
    frequency: 'Daily',
    tokenReward: 30,
    statBonuses: [{ stat: 'Persistence', value: 3 }],
    journeyId: '1',
    completed: false,
  },
  {
    id: '3',
    title: 'Watch 3 coding tutorials',
    icon: '💻',
    difficulty: 'Easy',
    frequency: 'Daily',
    tokenReward: 20,
    statBonuses: [{ stat: 'Intelligence', value: 2 }],
    journeyId: '1',
    completed: true,
  },
  {
    id: '4',
    title: '1hr weight training',
    icon: '🏋️',
    difficulty: 'Hard',
    frequency: 'Daily',
    tokenReward: 50,
    statBonuses: [
      { stat: 'Vitality', value: 5 },
      { stat: 'Energy', value: 3 },
    ],
    journeyId: '2',
    completed: false,
  },
  {
    id: '5',
    title: 'Drink 2L of water',
    icon: '💧',
    difficulty: 'Easy',
    frequency: 'Daily',
    tokenReward: 20,
    statBonuses: [
      { stat: 'Vitality', value: 2 },
      { stat: 'Energy', value: 2 },
    ],
    journeyId: '2',
    completed: true,
  },
  {
    id: '6',
    title: 'FaceTime a friend',
    icon: '📱',
    difficulty: 'Trivial',
    frequency: 'Weekly',
    tokenReward: 10,
    statBonuses: [{ stat: 'Charisma', value: 2 }],
    journeyId: '3',
    completed: false,
  },
]

export const storeItems: StoreItem[] = [
  {
    id: '1',
    name: 'MacBook Pro M4',
    icon: '💻',
    category: 'Equipment',
    price: 5000,
    currency: 'gem',
    purchased: false,
  },
  {
    id: '2',
    name: 'Trip to Paris',
    icon: '🇫🇷',
    category: 'Trip',
    price: 1000,
    currency: 'gem',
    purchased: false,
  },
  {
    id: '3',
    name: 'Boxing Glove',
    icon: '🥊',
    category: 'Equipment',
    price: 300,
    currency: 'gem',
    purchased: false,
  },
  {
    id: '4',
    name: 'Movie night',
    icon: '🎬',
    category: 'Experience',
    price: 300,
    currency: 'token',
    purchased: false,
  },
  {
    id: '5',
    name: 'Ice cream',
    icon: '🍦',
    category: 'Food',
    price: 50,
    currency: 'token',
    purchased: false,
  },
  {
    id: '6',
    name: 'Concert Ticket',
    icon: '🎫',
    category: 'Experience',
    price: 500,
    currency: 'gem',
    purchased: false,
  },
]

export const focusSessions: FocusSession[] = [
  {
    id: '1',
    title: 'Prototyping',
    icon: '🎨',
    skillName: 'Figma',
    skillColor: '#ff8fab',
    xpGained: 58,
    duration: 58,
    date: 'Dec 22, 2024 at 22:00',
  },
  {
    id: '2',
    title: 'app backend',
    icon: '💻',
    skillName: 'JavaScript',
    skillColor: '#6b8cff',
    xpGained: 104,
    duration: 104,
    date: 'Dec 22, 2024 at 21:01',
  },
  {
    id: '3',
    title: 'Practice calligraphy',
    icon: '✒️',
    skillName: 'Calligraphy',
    skillColor: '#ffa500',
    xpGained: 51,
    duration: 51,
    date: 'Dec 22, 2024 at 19:15',
  },
  {
    id: '4',
    title: 'Practice calculus',
    icon: '📊',
    skillName: 'Calculus',
    skillColor: '#00d4ff',
    xpGained: 70,
    duration: 70,
    date: 'Dec 22, 2024 at 18:22',
  },
  {
    id: '5',
    title: 'Code for 4 hours',
    icon: '💻',
    skillName: 'iOS development',
    skillColor: '#ff6b9d',
    xpGained: 163,
    duration: 163,
    date: 'Dec 19, 2024 at 17:59',
  },
]
